spring.application.name=analyzesystem
server.port=8779

spring.threads.virtual.enabled=true

joinfaces.primefaces.theme=bootstrap
joinfaces.faces.project-stage=Production

#input.folder=C:\\temp\\input
input.folder=/home/user/temp/input
#work.folder=C:\\temp\\work
work.folder=/home/user/temp/work/
default.csv.encoding=CP1251
default.csv.separator=;

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=asystem
spring.datasource.username=asystem_admin
spring.datasource.password=asystem_admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration for DDL Auto
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional: Show SQL queries in console
spring.jpa.show-sql=true

folders.path=/home/user/temp
folders.update.task.interval=300000

geolite.file=/home/user/temp/glc.mmdb