spring.application.name=analyzesystem
server.port=8779

spring.threads.virtual.enabled=true

joinfaces.primefaces.theme=vela
joinfaces.faces.project-stage=Production

input.folder=C:\\temp\\input
work.folder=C:\\temp\\work